settings:
  allItemsUnbreakable: true
  hideAllUnbreakable: true
  hideAllAttributes: true

itemLayout:
  - "!LORE"
  - "!ITEMTYPE"
  - "!STAT:physicalattack"
  - "!STAT:accuracy"
  - "!STAT:attackspeed"
  - "!STAT:health"
  - "!STAT:defense"